### ISSUE TITLE
第一次加载很慢，能优化吗？

### ISSUE THREAD

**Issue by zhi3210happy** [didilinkin/react-admin-antd#1]
有米有 使用异步加载？

**Comment by didilinkin** [comment]
还没用过 异步加载 和 webpack的优化功能， 现在项目需求的功能大体完成。  后期我将尝试做一些性能优化的内容。  是否有好的建议吗？  我将去尝试一下 谢谢 @zhi3210happy

**Comment by zhi3210happy** [comment]
账号密码是多少，直接访问/home能进去，没加验证吗？进去后数据获取不到，数据地址是否有误？是否要改api/api.dev 中的axios.defaults.baseURL 。
还有api/api.prod 为什么是空的。 以及build 后文件没有分割，没有按需加载。

**Comment by didilinkin** [comment]
@zhi3210happy   您好， 非常感谢您提出这些问题; 

1. 登录功能, 你可以退到 版本号为 `e2eb17bca83406d8c620a5df990a85748e6cd677`的地方进行测试； 最新版本 加入了公司项目的测试登录环境； 需要局域网内进行验证测试...  后台没做外网接口  我会尽快解决(做一个小按钮 一键设置LS的本地数据)。 这样就可以进行登录

2. 后台所有的数据都获取不到...  因为涉及到 公司内部数据...  我会尽快使用mock.js 来解决 模拟数据的获取。 或者从一些免费的API接口处 获取 数据 进行测试填充

3. axios的baseURL 的功能 也是下周之内 尽快解决。目前没有可用的 对外接口 ,  我明日就去咨询一下是否有不涉及公司隐私的 API数据 提供使用

3. 关于 prod 线上接口的文件 没有配置；  理由同上, 目前刚刚开发到部分业务逻辑功能。  线上数据 还没部署完成。  如果可以  我也会尽快完善

4. build 功能 暂未提供‘分割’ 与 ‘按需加载’功能；  我会将本项目从 公司业务逻辑内脱离出来 ， 作为一个 不涉及公司隐私的 开源项目后，  全部完善 以上功能；

非常感谢 您提出的 问题, 我会尽快去完善 并  优化

只是苦于目前 工作上的事情比较多，  还有一个移动端的Vue 任务 等待处理。  实在分身乏力， 望理解

谢谢 :joy:

**Comment by didilinkin** [comment]
登录的 方法已在 README 当中描述. 一键登录功能 未制作
