### ISSUE TITLE
config/paths.js文件是脚手架生成的吗？

### ISSUE THREAD

**Issue by pei-han** [didilinkin/react-admin-antd#10]
RT
@didilinkin

**Comment by didilinkin** [comment]
@pei-han  你好 ， 这个配置 是我从别人的脚手架那里摘出来的， 还比较好用

**Comment by pei-han** [comment]
@didilinkin  我看了react官方的脚手架程序create-react-app的依赖react-scripts，如下：
![image](https://user-images.githubusercontent.com/1300292/40477596-66998418-5f79-11e8-84ee-ced62f818db0.png)


有run-scripts脚本和一些类配置脚本，请问，为什么要单独抽出来，有什么用意，哪些地方做了自定义化？

**Comment by didilinkin** [comment]
@pei-han 之前应该是为了修改里面的配置， 需要一些个性化定制的内容。 所以用eject 把配置都暴露了。 之前好像是为了 sass 和 less的自定义配置 ， antd的按需加载吧。  现在不用了。 因为 antd 官方有教程 处理好这个配置问题了
