### ISSUE TITLE
访问http://localhost:3006/login产生编译错误

### ISSUE THREAD

**Issue by pei-han** [didilinkin/react-admin-antd#12]
![image](https://user-images.githubusercontent.com/1300292/40697285-20db3e8a-63fc-11e8-8743-bfb9d8cea084.png)
下面是根据错误提示的处理
![image](https://user-images.githubusercontent.com/1300292/40697307-3ba99158-63fc-11e8-9ae6-3bbe8894df82.png)
你那边有这种错误的情况吗？这个是不是与git clone时候对特殊字符处理有关

**Comment by didilinkin** [comment]
@pei-han  你好， 这个问题是因为 我是用了强制的语法纠正: 也就是说 你的 51, 52, 53 行其实都应该统一对齐的， 不可以这样缩进。 这是语法规范。 并不是 错误哦

这里是 eslint 详细说明 请查看 ： [indent](http://eslint.cn/docs/rules/indent)

**Comment by didilinkin** [comment]
我在 **.eslintrc.js** 文件中 也很详细的 记录了正确的语法规范内容， 绝对花心思了 哈哈， 请查看一下。 如果实在不喜欢， 可以自行修改规则。  推荐使用 社区写好的规范吧。 避免一人一套风格

**Comment by pei-han** [comment]
@didilinkin  正常来说，这个地方的缩进肯定是没问题的，因为我觉得你提交代码的时候肯定是做了很好的测试。那么，第二张图中的违反eslint缩进规范的情况出现是由于编辑器的缘故还是版本控制工具git的缘故？

**Comment by didilinkin** [comment]
@pei-han 首先确认， 其实写法肯定不会有问题； 如果我没记错 我的这份 语法规范 应该是完全按照 eslint-standard 来做的(有些小改动 和 加强) 。

我对eslint的配置 一般是 代码 热更新的时候会检查一遍， 代码提交的时候 git 钩子调用 eslint 再检查一遍(防止有人写 独立风格的 代码格式 push到gitlab管理当中， 这显然是很不好的)

如何解决: 修改 eslint rule 规则 就可以了， 钩子那里推荐不要动
