### ISSUE TITLE
点击Header内的表示折叠左侧菜单的图标，不起作用

### ISSUE THREAD

**Issue by pei-han** [didilinkin/react-admin-antd#13]
![image](https://user-images.githubusercontent.com/1300292/40776477-6873a762-64fd-11e8-8e06-c6be9aa1eca5.png)

**Comment by didilinkin** [comment]
期望 修改一下 PR 关于 router 的内容， 稍后会测试一下。 感谢提交修复 @pei-han

**Comment by pei-han** [comment]
@didilinkin  关于更新react-router文档URL的那个commit是上一次PR中的。
理论上不应该出现在这一次的PR中的，是不是我上次提的PR，你这边merge的时候有点问题导致的？

**Comment by didilinkin** [comment]
@pei-han 好的， 明天 我来处理一下吧

**Comment by didilinkin** [comment]
@pei-han  已合并， 请pull一下最新代码吧
