### ISSUE TITLE
build后部署在服务器上访问始终404.

### ISSUE THREAD

**Issue by zhi3210happy** [didilinkin/react-admin-antd#2]
试过nginx 
server {
  ...
  location / {
    try_files $uri /index.html
  }
}
和Apache 服务器
RewriteEngine On
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-l
RewriteRule ^.*$ / [L,QSA]
都不行，请问你这个应该怎么弄。
是否是路由的问题？

**Comment by didilinkin** [comment]
@zhi3210happy  你好， 建议尝试一下 服务地址 加一个'/' 访问; 如果还不好用, 可能是我这边的问题； 我这个项目的上一版本是可以直接跳向首页的；  

明天我去公司问一下， 看看服务器部署后 是否还存在这个问题； 

我会尽快解决

谢谢

**Comment by zhi3210happy** [comment]
不知道我的以上配置是否正确，您的nginx or Apache服务器配置是这样的吗？

**Comment by didilinkin** [comment]
@zhi3210happy 不好意思， 我们用的是 nginx 服务; 我只知道配置了一个重定向， 一直指向根路径; 至于配置内容  我不太清楚...  是后端去配置的。 不好意思

**Comment by superlbr** [comment]
@didilinkin  能否提供些demo的测试数据，便于调试开发，谢谢

**Comment by didilinkin** [comment]
@superlbr 您好， 我近期可能会做一点模拟用的 测试数据， 但是绝对不会像现在这种版本中 功能这么多( 因为有些需求是根据 项目来进行开发的， 需要后台人员的配合。 我一个人可能搞不出 那么多数据 和 功能 ) 如果有特别需要的 功能 可以描述一下； 我找找是否是我自己做的模拟数据； 谢谢

**Comment by superlbr** [comment]
@didilinkin 模拟数据也可以，谢谢。另外我对于多标签页的实现很感兴趣，能简单讲讲吗

**Comment by didilinkin** [comment]
@superlbr 感谢提问!

多标签页的实现 确实花了一番功夫， 简单来说它的实现是依靠 `Redux`来实现的；

因为首页是 固定的, 所以 首页状态一直在初始化当中， 而其他的 标签是在 **标签组件 - TabsContainers.jsx** 当中 检查 `nextProps`来更改；

当你在多个标签当中 点击触发切换的时候， 会将切换的 `activePane` 保存到 `Redux`当中, 然后再出发 `history`的 跳转 来切换

我一直没有处理好的 其实是 关于 多标签这个组建的 多次渲染问题( 之前 是将 多标签这个组件 跟 页面内容 组件放在一起的 )， 后来将它们分拆之后； 内容部分的组件( 业务逻辑 )只会 走一次， 不会被多次渲染 所影响； 而 多标签组件的多次渲染也不会产生其他的 负面影响， 所以暂时 是一个可行的解决方案

如果 你对哪里的 逻辑还有些不理解， 可直接 贴出那部分代码。 我会单独 讲解一下

谢谢
