### ISSUE TITLE
Failed to compile.

### ISSUE THREAD

**Issue by zhi3210happy** [didilinkin/react-admin-antd#3]
Failed to compile.

./node_modules/_rc-animate@2.4.1@rc-animate/es/AnimateChild.js
76:11-34 'css-animation' does not contain an export named 'isCssAnimationSupported'.

**Comment by didilinkin** [comment]
@zhi3210happy  你好， 我确认一下 开发环境

node - 7.10.0
npm - 4.2
yarn - 0.27.5

优先尝试一下 使用 yarn 安装一遍依赖。(需翻墙) 时间较长 一般撑死10分钟， 请耐心等待

其次尝试一下 npm 安装依赖

如果还不行的话， 使用 cnpm 安装一遍依赖

根据以上方法， 如果还不好用， 请 发一下你的 环境信息， 我尝试 还原一下试试

**Comment by zhi3210happy** [comment]
已使用cnpm安装 解决了。
