### ISSUE TITLE
路由看不懂能教一下吗？

### ISSUE THREAD

**Issue by aKaigege** [didilinkin/react-admin-antd#5]
谢谢大神

**Comment by didilinkin** [comment]
@aKaigege  嗨 你好， 感谢提出的疑问!

解释一下使用 router v4的初衷: 上一版本中, 本项目 左侧导航栏内容非常多( 甚至达到了4层 )， 产品还动不动大改结构... 因此决定将 路由系统改为 动态配置

介绍两个 核心文件位置:

`..\src\utils\globalDir.js`  —— 为 核心路由配置( 附带左侧导航栏输出 功能 )
`..\src\utils\globalDetailsRoute.js`  —— 为 ‘详情页’ 路由配置( 无左侧导航栏输出 功能 )

路由结构 建议阅读顺序:

1. `../src/router/index` —— 根文件
2. `../src/router/configRoutes.js` —— 配置 静态路由结构； 合并 'matchingRoutes' 业务匹配路由 ， 'basicRoute' 基础路由( 如 404， 登录页 等 )， 还有一个 验证信息路由
3.  最后就是 阅读 那三个 主要文件了: `matchingRoutes.js` , `basicRoutes.js`,  `privateRoutes.js`

如果还有疑问 欢迎 继续留言

谢谢!

**Comment by didilinkin** [comment]
里面使用了 [react-router-config](https://github.com/ReactTraining/react-router/tree/master/packages/react-router-config)来将 我们 输出的路由配置， 转化为 静态配置， 使用 ‘renderRoutes ’方法 

```js
// ../src/router/index.js
import { renderRoutes } from 'react-router-config'

const RouteView = ({ route }) => (
    <Switch> { renderRoutes(route.routes) } </Switch>
)
```
