### ISSUE TITLE
设置好 localstore 还是不能登录，请问用户名和密码是什么呢？

### ISSUE THREAD

**Issue by tryrefine** [didilinkin/react-admin-antd#8]

**Comment by didilinkin** [comment]
@tryrefine 你好， 感谢提问!

目前登录功能 要返回当前用户的权限， 还有可以看到的 左侧导航栏导航信息； 

所以 我有一部分 LS的数据 暂时还没有补上； 我周一的时候 会把内网里面的 LS模拟数据 记录一下； 更新到 README上；

你可以在周一的时候看到 具体的LS配置方法； 到时候就可以用啦

**Comment by tryrefine** [comment]
@didilinkin 好的，感谢

**Comment by didilinkin** [comment]
@tryrefine  您好， LS 需要的模拟数据已更新到 `README` 文档上, 可以测试了

**Comment by tryrefine** [comment]
@didilinkin 登录已经可以了，不过，由于系统需要访问后台获取数据，所以，在没有后台的情况下，数据获取不到，有很多脚本错误。比如：
192.168.5.250:18082/system/MenuList Failed to load resource: net::ERR_CONNECTION_TIMED_OUT

再比如：
Warning: Failed prop type: Invalid prop `size` of value `normal` supplied to `Select`, expected one of ["default","large","small"].

**Comment by didilinkin** [comment]
@tryrefine  你好。
第一个是请求 我们本地服务器的 服务器接口; 你肯定无法链接到的... 所有有超时提醒

第二个问题 应该是 `AntD`的选择器 组件, `props`接口出现错误; 可以换个页面看看; 不影响全局的

**Comment by tryrefine** [comment]
@didilinkin 
首先感谢您的回复，也感谢您的无私分享，这个项目大体看很不错。

如果您能 mock 一些数据，让这个项目在脱离后台接口服务器的情况下运转良好的话，使用者就能查看到更多页面效果，只有真正使用起来了，才能有更多的建议的反馈，同时也才能让使用和学习者受益更多。

项目跑起来了，但是看不到效果的话，会拦住一大群人，哈哈，就象这种前端小白...

**Comment by didilinkin** [comment]
@tryrefine 您好， 因为我本人正在处理离职的问题; 手上暂时有很多样式BUG 再改； 所以对于数据这块一直没太有时间好好处理一下；  本人也是非常着急；

我准备离职后， 重新把这个项目重写； 剥离掉公司的业务逻辑 和 代码, 数据的话 考虑用 Mockjs 做一些简单的 模拟数据； 但是 放点什么模拟数据呢， 还是有点头疼， 没想好 哈哈

如果是希望看到 mockjs 模拟数据 脱离后台进行演示的话， 可以看看 `https://github.com/didilinkin/Shangchao-pms-wx/tree/master/mock` 这个项目下的  mockjs模拟配置；

其实我还想试试 用Node 做个小后台 来处理 返回的数据， 苦于没时间学 Koa；  我会尽力去做好的

谢谢鼓励！

**Comment by tryrefine** [comment]
@didilinkin 嗯，理解理解，我也是每天只有下班之后才有时间学前端，白天工作时间与 java 打交道。
我 star 和 watch 了，期待您的更新哦。

**Comment by didilinkin** [comment]
@tryrefine  非常感谢， 共同学习 一起进步 哈哈

**Comment by pei-han** [comment]
@didilinkin  使用的是chrome，按照说明，设置了localStorage，访问/home及其子页面，仍旧转入/login登录页面，这是怎么回事？谢谢
