### ISSUE TITLE
scripts/start.js是脚手架生成的吗？

### ISSUE THREAD

**Issue by pei-han** [didilinkin/react-admin-antd#9]
看到这个文件里面有
// @remove-on-eject-begin
/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */
// @remove-on-eject-end

**Comment by didilinkin** [comment]
对 这段是从 create-react-app 配置出来的 比较通用
